//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoi_Truyen
    {
        public int userId { get; set; }
        public int truyenId { get; set; }
        public System.DateTime NgayTheoDoi { get; set; }
    
        public virtual Truyen Truyen { get; set; }
        public virtual Users Users { get; set; }
    }
}
