//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ID_ThongBao { get; set; }
        public int userId { get; set; }
        public string NoiDung { get; set; }
        public bool DaXem { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
