//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.Chuong = new HashSet<Chuong>();
            this.TheoDoi_Truyen = new HashSet<TheoDoi_Truyen>();
            this.ThuVien = new HashSet<ThuVien>();
        }
    
        public int truyenId { get; set; }
        public int userId { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public int TheLoaiId { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhap { get; set; }
        public int LuotDoc { get; set; }
        public bool XepLoai { get; set; }
        public bool DaDang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuong> Chuong { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoDoi_Truyen> TheoDoi_Truyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuVien> ThuVien { get; set; }
        public virtual Users Users { get; set; }
    }
}
