//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int BaoCaoId { get; set; }
        public Nullable<int> NguoiBaoCaoId { get; set; }
        public string LoaiBaoCao { get; set; }
        public int DoiTuongId { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
