//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int BinhLuanId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> truyenId { get; set; }
        public Nullable<int> ChuongId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        public virtual Truyen Truyen { get; set; }
        public virtual Users Users { get; set; }
    }
}
