//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoi_NguoiDung
    {
        public int TheoDoiNguoiDungId { get; set; }
        public int NguoiTheoDoiId { get; set; }
        public System.DateTime NgayTheoDoi { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
