//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_truyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuVien
    {
        public int UserID { get; set; }
        public int TruyenID { get; set; }
        public Nullable<int> ChuongDocGanNhat { get; set; }
        public Nullable<System.DateTime> ThoiGianDocGanNhat { get; set; }
        public Nullable<bool> CoLuu { get; set; }
        public Nullable<bool> DocXong { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        public virtual Truyen Truyen { get; set; }
        public virtual Users Users { get; set; }
    }
}
